project:
  type: website
  title: "Penguins 2"
  
website:
  navbar:
    background: "#cad4eb"
    search: true
    left:
      - index.qmd
      - eda.qmd
      - model.qmd
      - penguins.qmd

editor: visual